version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - pip install aws-sam-cli
    build:
      commands:
        - sam build
      post_build:
        commands:
          - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
          